version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gamers-app
    env_file:
      - ../env/.env
    ports:
      - "8080:8080"
    networks:
      - gamers-network
    restart: unless-stopped

networks:
  gamers-network:
    driver: bridge