services:
  redis:
    image: redis:7-alpine
    container_name: gamers-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ] # Data Persistence ON
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - gamers-network
    restart: unless-stopped
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gamers-app
    env_file:
      - ../env/.env
    ports:
      - "8080:8080"
    networks:
      - gamers-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

networks:
  gamers-network:
    driver: bridge

volumes:
  redis_data: